### ISSUE TITLE
大佬，icon怎么弄啊

### ISSUE THREAD

**Issue by sdfsfs-star** [zx1984/image-view#13]

**Comment by capricorncd** [comment]
icon参考这个 http://www.iconfont.cn/
名称和文档上的一样即可：
如: 关闭图标，icon名称为`zx-close`
https://github.com/capricorncd/zx-image-viewer/blob/master/README.md#%E9%99%84%E5%BD%95
链接可能失效：
https://github.com/capricorncd/zx-image-viewer/blob/v1.5.0/README.md#%E9%99%84%E5%BD%95
https://github.com/capricorncd/zx-image-viewer/blob/v1.5.x/README.md#%E9%99%84%E5%BD%95
